### PR TITLE
Adding indraastra to contributors

### PR DESCRIPTION
**Pull request by indraastra**

### CODE REVIEW

**Comment by affinity-matrix** [comment]
Thank you, @indraastra! 

One more thing: would you mind signing our CLA? Thanks!
https://docs.google.com/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

**Comment by affinity-matrix** [comment]
Also if possible, would you mind rebasing against the recent merge of @msolters' PR? :smile_cat: 

(#8)

**Comment by indraastra** [comment]
Done and done!

**Comment by affinity-matrix** [comment]
Yay! Thanks a bunch! :grinning:

**Pull request merged**
