### PR TITLE
Factored out the core SoftAP code to make it Browserify-friendly.

### PR DESCRIPTION
**Pull request by brewnerd**
SoftAP can now be run in the browser. Updated README.md with instructions. Tests pass. No change to repl or existing usage.

### CODE REVIEW

**Comment by brewnerd** [comment]
Firefox had clean javascript output. Chrome had 2 warnings, but no adverse effects:

softap-setup-js_browserify

**Comment by msolters** [comment]
Clean output in Chrome over here (Ubuntu 1504).  I have one question -- not sure if this is specific to the browserified implementation, but the values for `.sec` from the AP scan results are all int.  What is the mapping from those integers to the security type strings as listed ine the `softap-setup-js` readme?  I gather `sec: 0` == no security but beyond that is there a table or a mapping function somewhere that I am missing?

**Comment by brewnerd** [comment]
@msolters Here's the mapping from `softap.js`:

`var securityTable = {
  "open": 0,
  "none": 0,
  "wep_psk": 1,
  "wep_shared": 0x8001,
  "wpa_tkip": 0x00200002,
  "wpa_aes": 0x00200004,
  "wpa2_aes": 0x00400004,
  "wpa2_tkip": 0x00400002,
  "wpa2_mixed": 0x00400006,
  "wpa2": 0x00400006
};`

Convert the decimal value you get from the scan() call to hex.

**Comment by msolters** [comment]
Oh!  I just found `SoftAP.prototype.securityLookup(dec) -> str` in the Browserified JS output, which is exactly what I was looking for!  Thanks for pointing me in the right direction.

**Comment by affinity-matrix** [comment]
@brewnerd wow hey!

This is an amazing PR! Thank you so much for this! :100: 
I just got back from vacation, and everything looks great but I want to take the time to play with it and make sure others on the team have had a chance to take a look.

This is really great, thank you again!

:tada:

**Pull request merged**
